name: Build macOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos-app:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PySide6 pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --clean --onefile --windowed --add-data="building_data.json:." --add-data="styles/main.css:styles" main.py

    - name: Remove macOS quarantine attribute
      run: |
        xattr -d com.apple.quarantine dist/main  || true

    - name: Upload macOS executable
      uses: actions/upload-artifact@v4
      with:
        name: StroyCent
        path: dist/main
