name: Build macOS app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install PySide6 pyinstaller


    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --windowed --add-data "building_data.json;." --add-data "styles/main.css;styles" main.py





    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: dist/main
